plugins:
  - jekyll-seo-tag

title: alkitabsaja
description: Firman Tuhan Tanpa Salah
url: https://www.diselamatkan.org
logo: https://github.com/alkitabsaja.png
favicon: /assets/favicon.ico
markdown: kramdown

twitter:
  username: alkitabsaja

social:
  name: AlkitabSaja
  links:
    - https://github.com/alkitabsaja

collections:
  docs:
    output: true
    permalink: /docs/:name/

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

nav:
    - title: Home
      url: /
    - title: Docs
      url: /docs/
