title: @alkitabsaja
description: follow and share
logo: https://github.com/alkitabsaja.png
favicon: /assets/favicon.ico
markdown: kramdown

collections:
  docs:
    output: true
    permalink: /:collection/:name/

nav:
    - title: Home
      url: /
    - title: Docs
      url: /docs/
