title: @alkitabsaja
description: follow and share
markdown: kramdown
theme: null

collections:
  docs:
    output: true
    permalink: /docs/:name/

nav:
    - title: Home
    url: /
    - title: Docs
    url: /docs/
