name: Build All

permissions:
  contents: write

on:
  push:
    paths:
      - "_docs/**/*.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Pandoc + LaTeX + rss
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-fonts-recommended
          npm install -g neocities
          pip install feedparser
          python .github/scripts/rss.py

      - name: Build PDFs & EPUBs
        shell: bash
        run: |
          set -euo pipefail
          tree -L 2

          mkdir -p ebooks
          shopt -s globstar nullglob

          for src in _docs/**/*.md; do
            rel="${src#_docs/}"
            out="${rel%.md}"

            mkdir -p "ebooks/$(dirname "$out")"

            echo "Building $rel"
            BUILD_DATE="$(date -u '+%Y-%m-%d %H:%M UTC')"
            echo "built at ${BUILD_DATE}" >> pandoc/footer.md
            tmp=$(mktemp)
            sed 's#](/assets/#](./assets/#g' "$src" > "$tmp"

            pandoc "$tmp" pandoc/footer.md \
              --defaults=pandoc/defaults.yml \
              --metadata=date="$BUILD_DATE" \
              --metadata=revision="${GITHUB_SHA::7}" \
              -o "ebooks/${out}.pdf"

            pandoc "$tmp" pandoc/footer.md \
              --defaults=pandoc/defaults.yml \
              --metadata=date="$BUILD_DATE" \
              --metadata=revision="${GITHUB_SHA::7}" \
              -o "ebooks/${out}.epub"
          done

      - name: Show generated files
        run: find ebooks -type f | sort

      - name: Commit generated ebooks
        run: |
          set -e

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add ebooks
          git add _docs/news

          if ! git diff --cached --quiet; then
            git commit -m "Update ebooks"
            git push
          fi
