name: Build All

permissions:
  contents: write
  pages: write
  id-token: write


on:
  push:
    paths:
      - "_docs/**/*.md"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:latest-ubuntu
      
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Pandoc + LaTeX + npm + pip
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended
          npm install -g surge pagefind
          npm list -g
          pagefind --version
          pip install feedparser
          pip list
          ruby -v
          bundle version
          
      - name: Build RSS, PDFs & EPUBs
        shell: bash
        run: |
          set -euo pipefail
          python .github/scripts/rss.py
          #tree -L 2

          mkdir -p ebooks
          shopt -s globstar nullglob

          for src in _docs/**/*.md; do
            rel="${src#_docs/}"
            out="${rel%.md}"

            mkdir -p "ebooks/$(dirname "$out")"

            echo "Building $rel"
            BUILD_DATE="$(date -u '+%Y-%m-%d %H:%M UTC')"
            echo "built at ${BUILD_DATE}" >> pandoc/footer.md
            tmp=$(mktemp)
            sed 's#](/assets/#](./assets/#g' "$src" > "$tmp"

            pandoc "$tmp" pandoc/footer.md \
              --defaults=pandoc/defaults.yml \
              --metadata=date="$BUILD_DATE" \
              --metadata=revision="${GITHUB_SHA::7}" \
              -o "ebooks/${out}.pdf"

            pandoc "$tmp" pandoc/footer.md \
              --defaults=pandoc/defaults.yml \
              --metadata=date="$BUILD_DATE" \
              --metadata=revision="${GITHUB_SHA::7}" \
              -o "ebooks/${out}.epub"
          done

      - name: Commit generated ebooks
        run: |
          set -e
          tree -L 3

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add feed.xml
          git add ebooks
          git add _includes/news.md
          #git add _docs/news
          #git add _docs/news.md

          if ! git diff --cached --quiet; then
            git commit -v -m "Update ebooks"
            git push -v
          fi

      - uses: actions/configure-pages@v5

      - name: Build and pagefind index
        run: |
          bundle exec jekyll build
          ls -al _site
          #chmod +w _site
          pagefind -v --glob "docs/**/*.{html}" --site _site

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4

      - name: Deploy to Surge
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          tree -L 2 ./_site
          surge ./_site https://alkitabsaja.surge.sh

